### ISSUE TITLE
Paragraph Vector algorithms

### ISSUE THREAD

**Issue by jwijffels** [maxoodf/word2vec#12]
Do you have any plans to add the distributed bag of words ('PV-DBOW') and the distributed memory ('PV-DM') model?

**Comment by maxoodf** [comment]
I think modern algorithms based on transformers, such as BERT and GPT, outperform Paragraph Vector, Average Vector and other old school algorithms on most of NLP tasks. So I do not plan to add PV implementations.

**Comment by jwijffels** [comment]
Ok. Fair enough. Thanks for the response.
