### ISSUE TITLE
Distance Between Two Words

### ISSUE THREAD

**Issue by VedhasWalke** [maxoodf/word2vec#14]
Do you provide any functionality to find the distance between two words? If there is no such functionality and you do not plan implement it, I can probably put together a simple distance function based on the cosine similarity metric, if you brief me on the format of your .w2v files, and commit it here if you would like.

**Comment by maxoodf** [comment]
I think [here](https://github.com/maxoodf/word2vec/blob/21e7f713477109047d4d8d32bf4dbf03b6ce5261/include/word2vec.hpp#L178) is what are you looking for.
