### ISSUE TITLE
w2c_accuracy failure

### ISSUE THREAD

**Issue by PatrickMalolepszy** [maxoodf/word2vec#3]
Using model trained from w2v_trainer.

```
time ./w2v_accuracy model.w2v ../../../word2vec/questions-phrases.txt 
 newspapers
 ice_hockey
 basketball
 airlines
section accuracy: 0.124119
 people-companies
terminate called after throwing an instance of 'std::ios_base::failure'
  what():  basic_ios::clear
Aborted
```

**Comment by maxoodf** [comment]
Hi Patrick,
It looks like you are using "questions-phrases.txt" from the original word2vec code, but its format is incompatible with w2v_accuracy. Try to use "questions-words.txt" instead of "questions-phrases.txt.
Max.
